AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PreviewReadWriteCapacity:
    Type: String
    Description: Read/Write Capacity of the PROD table
  LiveReadWriteCapacity:
    Type: String
    Description: Read/Write Capacity of the PROD table
  Stage:
    Type: String
    Description: Stage for the tables
    AllowedValues:
      - DEV
      - CODE
      - PROD
Resources:
  AtomWorkshopPreviewDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub atom-workshop-preview-${Stage}
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref PreviewReadWriteCapacity
        WriteCapacityUnits: !Ref PreviewReadWriteCapacity
  AtomWorkshopLiveDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub atom-workshop-live-${Stage}
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref LiveReadWriteCapacity
        WriteCapacityUnits: !Ref LiveReadWriteCapacity