AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PreviewReadCapacity:
    Type: String
    Description: Read Capacity of the PROD table
  PreviewWriteCapacity:
    Type: String
    Description: Write Capacity of the PROD table
  LiveReadCapacity:
    Type: String
    Description: Read Capacity of the PROD table
  LiveWriteCapacity:
    Type: String
    Description: Write Capacity of the PROD table
  Stage:
    Type: String
    Description: Stage for the tables
    AllowedValues:
      - DEV
      - CODE
      - PROD
  ReaderQuestionsDynamoRole:
    Type: String
    Description: ARN of the Readers Questions DynamoDB read role
Resources:
  AtomWorkshopPreviewDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub atom-workshop-preview-${Stage}
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "atomType"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "atomType"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref PreviewReadCapacity
        WriteCapacityUnits: !Ref PreviewWriteCapacity
  AtomWorkshopLiveDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub atom-workshop-live-${Stage}
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "atomType"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "atomType"
          KeyType: "HASH"
        - AttributeName: "id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: !Ref LiveReadCapacity
        WriteCapacityUnits: !Ref LiveWriteCapacity
  AssumeReaderQuestionsDynamoRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: assume-rq-db-role
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Resource:
            Ref: ReaderQuestionsDynamoRole
      Roles:
      - Ref: Role
Outputs:
  PreviewDynamoTableOut:
    Description: Table name for Preview dynamo table
    Value: !Ref AtomWorkshopPreviewDynamoTable
    Export:
      Name: !Sub ${AWS::StackName}-PreviewDynamoTableName
  PreviewDynamoArnOut:
    Description: ARN for Preview dynamo table
    Value: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AtomWorkshopPreviewDynamoTable}
    Export:
      Name: !Sub ${AWS::StackName}-PreviewDynamoTableArn
  LiveDynamoTableOut:
    Description: Table name for Live dynamo table
    Value: !Ref AtomWorkshopLiveDynamoTable
    Export:
      Name: !Sub ${AWS::StackName}-LiveDynamoTableName
  LiveDynamoArnOut:
    Description: ARN for Live dynamo table
    Value: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AtomWorkshopLiveDynamoTable}
    Export:
      Name: !Sub ${AWS::StackName}-LiveDynamoTableArn
