name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Build deployment artifacts
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: guardian/setup-scala@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: CI yarn
        shell: bash
        run: |
          yarn install --force --frozen-lockfile
          yarn lint
          yarn test
          yarn build

      - name: CI sbt
        shell: bash
        run: |
          sbt clean compile test Debian/packageBin

      - name: Upload to riff-raff
        uses: guardian/actions-riff-raff@v4
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          buildNumberOffset: 1319
          projectName: editorial-tools:atom-workshop
          configPath: riff-raff.yaml
          contentDirectories: |
            atom-workshop:
              - target/atom-workshop_1.0_all.deb
